name: Daily SonarQube Scan (Maven)

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
  workflow_dispatch:
    inputs:
      note:
        description: 'Manual trigger'
        required: false

jobs:
  sonarQubeScan:
    if: github.ref == 'refs/heads/main'  # Ensure it only runs on master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarQube Scanner with Maven
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B test -Pcoverage verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey="whitej031788_demo-java-security_23c25f38-ad3f-457c-8faf-5dcadd7de422" \
            -Dsonar.projectName="Java Web App" \
            -Dsonar.javaOpts="-Xmx8192m " \
            -Dsonar.sources="." \
            -Dsonar.exclusions="src/test/java/**/*" \
            -Dsonar.tests="src/test/java" \
            -X
